global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-ec2"
    static_configs:
      - targets: ["<YOUR_EC2_PRIVATE_IP>:9100"]

  - job_name: "node-kind"
    static_configs:
      - targets: ["localhost:9101"] # Matches the SSH tunnel port
